name: QA Tests and Publish

on:
  push:
  workflow_dispatch:

permissions:                  
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-qa-image .
      - name: Run QA tests in Docker
        run: |
          mkdir -p artifacts
          docker run --rm \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e WAF_SECRET_HEADER="${{ secrets.AWS_WAF_SECRET }}" \
            -v ${{ github.workspace }}/artifacts:/app/artifacts \
            my-qa-image
      - name: Generate HTML report
        run: |
          pip install jinja2
          python scripts/generate_html_report.py
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: docs

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: pages
